### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Tosd0** [Colter23/genshin-sign-mirai-plugin#13]
出现如题所说报错QAQ之前单独启动成功过，这次装了其他插件并且把原来文件夹下的data拖过来了就不行了……麻烦您帮忙qwq，谢谢！🙏
尝试过重启，未能解决。
### 版本信息：
Backend: version 2.13.0-RC2, built on 2022-10-21 01:15:53.
Frontend Terminal: version 2.13.0-RC2, provided by Mamoe Technologies
Java版本：
```
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```
### 插件
![image](https://user-images.githubusercontent.com/65720409/197387546-28bc2a2d-5e31-48f8-ac1f-5259d3081976.png)
### 有关报错
```
2022-10-23 18:07:26 I/GenshinSign: Genshin Plugin loaded
2022-10-23 18:07:26 E/GenshinSign: java.lang.NoClassDefFoundError: net/mamoe/mirai/console/util/CoroutineScopeUtils
java.lang.NoClassDefFoundError: net/mamoe/mirai/console/util/CoroutineScopeUtils
	at genshin-sign-mirai-plugin-0.3.7.mirai.jar//top.colter.mirai.plugin.genshin.Listener.<init>(Listener.kt:21)
	at genshin-sign-mirai-plugin-0.3.7.mirai.jar//top.colter.mirai.plugin.genshin.Listener.<clinit>(Listener.kt)
	at genshin-sign-mirai-plugin-0.3.7.mirai.jar//top.colter.mirai.plugin.genshin.PluginMain.onEnable(PluginMain.kt:40)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:279)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:194)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:194)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.util.CoroutineScopeUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:402)
	... 28 more

```
Config.yaml

```
# 管理员账号
admin: xxxxx
# 签到时间(0-23)
signTime: 7
# 模式
# 1: 单用户模式
# 2: 多用户模式
mode: 1
# 教程描述
# {cookie-img} 为在插件数据路径下的cookie.png图片
desc: "请用电脑访问米游社并登陆 https://bbs.mihoyo.com/ys/\n之后按照下图的步骤获取cookie\n并把cookie发送给bot\n(图片发送可能存在一定延迟){cookie-img}"

```

**Comment by 33333s** [comment]
同问
