### ISSUE TITLE
自动签到出现报错

### ISSUE THREAD

**Issue by icedlemon233** [Colter23/genshin-sign-mirai-plugin#5]
首先，我设置了每天0点自动签到。如果我在0点之前就一直开着MCL，那么自动签到可以正常运作。但是如果我在0点之后才打开MCL（例如00:02）那就会出现如下报错。

2022-03-04 00:28:03 W/GenshinSign: 对[1259386865]构建消息失败
java.lang.IllegalArgumentException: 找不到联系人
        at top.colter.mirai.plugin.genshin.GenshinTasker.signAction(GenshinTasker.kt:284)
        at top.colter.mirai.plugin.genshin.GenshinTasker.sign(GenshinTasker.kt:73)
        at top.colter.mirai.plugin.genshin.GenshinTasker$listen$1.invokeSuspend(GenshinTasker.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Colter23** [comment]
插件在mcl登录成功qq之前就完成了签到并想要发送信息，所以会出现这种情况（找不到联系人

**Comment by icedlemon233** [comment]
好家伙，竟然是因为签到得太快了。
